### ISSUE TITLE
"Open Web UI" uses HTTPS with ssl disabled

### ISSUE THREAD

**Issue by brianhanifin** [hassio-addons/addon-mqtt#40]
# Problem/Motivation

I fought with this for hours in Safari, just to discover an SSL error in Chrome. Shame on me, I should have tried that sooner. 🤦‍♂

My server is behind Wireguard so is not public facing, so I am no longer concerned with SSL.

## Expected behavior

When `"ssl": false` is set, http should be the chosen protocol instead of https.
Desired URL = `http://[localip]:5713`

## Actual behavior

The browser opened with `https://[localip]:5713`.

## Steps to reproduce

```yaml
{
  "log_level": "info",
  "certfile": "",
  "keyfile": "",
  "web": {
    "enabled": true,
    "ssl": false
  },
  "broker": {
    "enabled": true,
    "enable_ws": true,
    "enable_mqtt": true,
    "enable_ws_ssl": false,
    "enable_mqtt_ssl": false,
    "allow_anonymous": true
  },
  "mqttusers": [
    {
      "username": "mqttusername",
      "password": "mqttpassword",
      "readonly": false,
      "topics": [
        "#"
      ]
    }
  ],
  "leave_front_door_open": true
}
```

## Proposed changes

I propose that you add an `if` statement when defining the OPEN WEB UI url. 😉
